apiVersion: v1
kind: Service
metadata:
  name: zip2nist-service
  namespace: team-tikchalal
  labels:
    app: zip2nist
    project: zip2nist
    env: dev
spec:
  selector:
    app: zip2nist
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP
