apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip2nist
  namespace: tikchalal-prod-dvash
  labels:
    app: zip2nist
    project: zip2nist
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zip2nist
  template:
    metadata:
      labels:
        app: zip2nist
        project: zip2nist
        env: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2222"
    spec:
      serviceAccountName: tabalab-sa
      imagePullSecrets:
        - name: tikchalal-prod-pat
      containers:
        - name: zip2nist
          image: 651898668523.dkr.ecr.il-central-1.amazonaws.com/digitalidf/zip2nist/zip2nist:99aaf5e5bb5a
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: temp
          ports:
            - containerPort: 4000
          imagePullPolicy: Always

      volumes:
        - name: temp
          emptyDir:
            sizeLimit: 500Mi
