name: (Prod) Build, Push, Update Tag 
permissions: write-all

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/**'
      - '.github/workflows/**'
  workflow_dispatch:
jobs: 
  get-short-sha:
    outputs:
      SHORT_SHA: ${{ steps.get_short_sha.outputs.SHORT_SHA }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Get short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short=12 HEAD)" >> "$GITHUB_OUTPUT"

  build-and-push-preprod:
    needs: [ get-short-sha ]
    uses: digitalidf/tik-chalal/.github/workflows/general-build.yml@master
    with:
      prod_account_name: 'hr'
      image: 'zip2nist'
      version: '${{ needs.get-short-sha.outputs.SHORT_SHA }}'
      github_env: 'preprod'
      system_name: 'zip2nist'

  update-image-tag:
    needs: [ build-and-push-preprod, get-short-sha ]
    uses: digitalidf/tik-chalal/.github/workflows/update-tag.yml@master
    with:
      black_manifest_path: manifests/preprod/black/deployment.yaml
      dvash_manifest_path: manifests/preprod/dvash/deployment.yaml
      sha: ${{ needs.get-short-sha.outputs.SHORT_SHA }} 
    permissions:
      contents: write
    secrets: inherit

  lock-prod-update:
    needs: [ update-image-tag ]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Approve production release to continue
        run: echo "Approve production release to continue"

  update-prod-manifests-image-tag:
    needs: [ lock-prod-update, get-short-sha ]
    uses: digitalidf/tik-chalal/.github/workflows/update-tag.yml@master
    with:
      black_manifest_path: manifests/prod/black/deployment.yaml
      dvash_manifest_path: manifests/prod/dvash/deployment.yaml
      sha: ${{ needs.get-short-sha.outputs.SHORT_SHA }} 
    permissions:
      contents: write
    secrets: inherit