name: deploy-to-prod

on:
  workflow_call:
    inputs:
      app_name:
        description: "Application name"
        required: true
        type: string
      k8s_namespace:
        description: "Kubernetes namespace"
        required: true
        type: string

jobs:
  deploy-prod:
    runs-on: [self-hosted, aws, ec2runner, "hr-il"]
    environment:
      name: production

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository name as lower case string
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Pull the latest preprod image
        run: docker pull ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.app_name }}:preprod

      - name: Tag the preprod image as production
        run: docker tag ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.app_name }}:preprod ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.app_name }}:production

      - name: Push the production image
        run: docker push ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.app_name }}:production

      - name: Clean up - Delete pulled and local preprod image
        run: |
          docker image rm ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.app_name }}:preprod

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: il-central-1
          role-duration-seconds: 3600
      - name: Rollout deployment restart
        run: |
          kubectl rollout restart deployment ${{ inputs.app_name }} --namespace ${{ inputs.k8s_namespace }}
